theme: jekyll-theme-cayman
title: Bruno's Portfolio
description: Data Analytics projects, visualizations, and tech explorations by Bruno del Palacio Rodríguez
logo: https://avatars.githubusercontent.com/u/brunodpl
show_downloads: true
